package camelinaction.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2019-05-29T09:56:13.907-05:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://order.camelinaction", name = "OrderEndpoint")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OrderEndpoint {

    @WebMethod(action = "http://order.camelinaction/Order")
    @WebResult(name = "resultCode", targetNamespace = "http://order.camelinaction", partName = "resultCode")
    public java.lang.String order(
        @WebParam(partName = "parameters", name = "purchaseOrder", targetNamespace = "http://order.camelinaction")
        PurchaseOrder parameters
    );
}
