package camelinaction.order;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2019-05-29T09:56:13.953-05:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "OrderEndpointService", 
                  wsdlLocation = "classpath:wsdl/order.wsdl",
                  targetNamespace = "http://order.camelinaction") 
public class OrderEndpointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://order.camelinaction", "OrderEndpointService");
    public final static QName OrderService = new QName("http://order.camelinaction", "OrderService");
    static {
        URL url = OrderEndpointService.class.getClassLoader().getResource("wsdl/order.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(OrderEndpointService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/order.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public OrderEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderEndpointService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OrderEndpointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrderEndpointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrderEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OrderEndpoint
     */
    @WebEndpoint(name = "OrderService")
    public OrderEndpoint getOrderService() {
        return super.getPort(OrderService, OrderEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderEndpoint
     */
    @WebEndpoint(name = "OrderService")
    public OrderEndpoint getOrderService(WebServiceFeature... features) {
        return super.getPort(OrderService, OrderEndpoint.class, features);
    }

}
